name: Update YouTube in README

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

jobs:
  update-youtube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Uses RSS to pull latest videos and write into README
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCbPgTxewc1ofPsDoZjMis3g"
          max_post_count: 6
          readme_path: "./README.md"
          comment_tag_name: "YOUTUBE"
          commit_message: "⚡ update YouTube feed"
